### ISSUE TITLE
مشکل پوشه gen

### ISSUE THREAD

**Issue by MBehtemam** [hamedjj/BazaarInAppBilling#5]
سلام  و تشکر. من مطابق پروژه بازار عمل کردم و از پروژه شما هم برای ساخت پروژه خودم کمک گرفتم اما پوشه 
gen
ساخته نشد حتی بعد از بیلد کردن.

**Comment by hamedjj** [comment]
http://stackoverflow.com/questions/11305208

http://stackoverflow.com/questions/13927759

**Comment by MBehtemam** [comment]
thanks it's solved.
