### ISSUE TITLE
خطای Not allowed to bind to service Intent 

### ISSUE THREAD

**Issue by MBehtemam** [hamedjj/BazaarInAppBilling#6]
سلام.  نمی دونم این خطا می تواند از عدم تولید پوشه جنریت باشد یا نه . اما من این خطا را در کد زیر میگیرم 

       mHelper.startSetup(new IabHelper.OnIabSetupFinishedListener() {
            public void onIabSetupFinished(IabResult result) {
                Log.d(TAG, "Setup finished.");

                if (!result.isSuccess()) {
                    // Oh noes, there was a problem.
                    Log.d(TAG, "Problem setting up In-app Billing: " + result);
                }
                // Hooray, IAB is fully set up!
                mHelper.queryInventoryAsync(mGotInventoryListener);

            }
        });

با جستجو در اینترنت چه انگلیسی و چه فارسی اکثرا گفته بودند که مشکل می تواند از مانیفست باشد که مجوز ندارد که مجوز دارد و برنامه بازار هم هم روی گوشی هم روی امولاتور است و هر دو هم لاگین شده هستند ؟ اما باز این مشکل وجود دارد.

**Comment by hamedjj** [comment]
http://barnamenevis.org/showthread.php?510697

**Comment by MBehtemam** [comment]
thanks it solved.
